[package]
name = "task-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.16", features = ["cargo", "derive"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
